import type {GraveEntry} from './types'

// Your graveyard. Each entry becomes a published bug in Sanity:
//
//   npx sanity exec scripts/import-graves.ts --with-user-token -- --dry-run   check first
//   npx sanity exec scripts/import-graves.ts --with-user-token                import
//
// Re-running updates the same bugs in place. Every field is explained in ./types.ts.

export const graves: GraveEntry[] = [
  {
    key: 'loop-skipped-last',
    name: 'Loop that skipped the last item',
    language: 'Python',
    cause: 'Off-by-one',
    status: 'buried',
    severity: 'low',
    epitaph: 'Almost made it to the end. Almost.',
    killedBy: 'Jashanpreet',
    hoursToKill: 3,
    bornAt: '2024-02-12',
    fixMergedAt: '2024-02-15',
    buriedAt: '2024-02-26',
  },
  {
    key: 'undefined-not-function',
    name: 'undefined is not a function',
    language: 'JavaScript',
    cause: 'Null reference',
    status: 'buried',
    severity: 'medium',
    epitaph: 'It was never a function. It was never anything.',
    killedBy: 'Jashanpreet',
    hoursToKill: 2,
    bornAt: '2024-04-03',
    fixMergedAt: '2024-04-04',
    buriedAt: '2024-04-15',
  },
  {
    key: 'floating-invoice',
    name: 'The 0.1 + 0.2 invoice',
    language: 'JavaScript',
    cause: 'Floating point',
    status: 'buried',
    severity: 'critical',
    epitaph: 'Owed ₹0.30000000000000004. Paid in full.',
    killedBy: 'Jashanpreet',
    hoursToKill: 9,
    bornAt: '2024-06-17',
    fixMergedAt: '2024-06-21',
    buriedAt: '2024-07-01',
  },
  {
    key: 'div-center',
    name: 'The div that refused to center',
    language: 'CSS',
    cause: 'CSS',
    status: 'buried',
    severity: 'low',
    epitaph: 'Stood slightly to the left of everything, forever.',
    killedBy: 'Jashanpreet',
    hoursToKill: 6,
    bornAt: '2024-08-05',
    fixMergedAt: '2024-08-09',
    buriedAt: '2024-08-19',
  },
  {
    key: 'my-machine',
    name: "Works only on Jashan's laptop",
    language: 'Python',
    cause: 'Works on my machine',
    status: 'buried',
    severity: 'medium',
    epitaph: 'It worked on my machine. Now it rests there.',
    killedBy: 'Jashanpreet',
    hoursToKill: 14,
    bornAt: '2024-09-23',
    fixMergedAt: '2024-10-01',
    buriedAt: '2024-10-10',
  },
  {
    key: 'dst-cron',
    name: 'Cron job that ran twice at DST',
    language: 'Java',
    cause: 'Timezone',
    status: 'buried',
    severity: 'critical',
    epitaph: 'Died twice in one night. Twice as dead.',
    killedBy: 'Jashanpreet',
    hoursToKill: 11,
    bornAt: '2024-10-27', // the night European clocks fell back an hour
    fixMergedAt: '2024-11-04',
    buriedAt: '2024-11-13',
  },
  {
    key: 'stale-cache',
    name: 'Stale cache after deploy',
    language: 'TypeScript',
    cause: 'Cache',
    status: 'buried',
    severity: 'medium',
    epitaph: 'Showed you yesterday, every day.',
    killedBy: 'Jashanpreet',
    hoursToKill: 7,
    bornAt: '2025-01-14',
    fixMergedAt: '2025-01-17',
    buriedAt: '2025-01-28',
  },
  {
    key: 'npm-install',
    name: 'npm install broke the build',
    language: 'JavaScript',
    cause: 'Dependency hell',
    status: 'buried',
    severity: 'critical',
    epitaph: 'Killed by a package it never imported.',
    killedBy: 'Jashanpreet',
    hoursToKill: 4,
    bornAt: '2025-03-10',
    fixMergedAt: '2025-03-11',
    buriedAt: '2025-03-20',
  },
  {
    key: 'race-counter',
    name: 'Two threads, one counter',
    language: 'Java',
    cause: 'Race condition',
    status: 'buried',
    severity: 'critical',
    epitaph: 'Both threads won. The counter lost.',
    killedBy: 'Jashanpreet',
    hoursToKill: 38,
    bornAt: '2025-04-22',
    fixMergedAt: '2025-05-09',
    buriedAt: '2025-05-19',
  },
  {
    key: 'while-true',
    name: 'while (true) with no break',
    language: 'C++',
    cause: 'Infinite loop',
    status: 'buried',
    severity: 'medium',
    epitaph: 'Still running. Please do not disturb.',
    killedBy: 'Jashanpreet',
    hoursToKill: 1,
    bornAt: '2025-06-30',
    fixMergedAt: '2025-07-01',
    buriedAt: '2025-07-10',
  },
  {
    key: 'emoji-username',
    name: 'Emoji broke the username',
    language: 'Python',
    cause: 'Encoding',
    status: 'buried',
    severity: 'medium',
    epitaph: "Here lies Ã©. It was once 'é'.",
    killedBy: 'Jashanpreet',
    hoursToKill: 12,
    bornAt: '2025-08-11',
    fixMergedAt: '2025-08-19',
    buriedAt: '2025-08-28',
  },
  {
    key: 'merge-head',
    name: '<<<<<<< HEAD in production',
    language: 'TypeScript',
    cause: 'Merge conflict',
    status: 'buried',
    severity: 'critical',
    epitaph: 'Both versions were right. Neither survived.',
    killedBy: 'Jashanpreet',
    hoursToKill: 1,
    bornAt: '2025-11-03',
    fixMergedAt: '2025-11-04',
    buriedAt: '2025-11-12',
  },
  {
    key: 'index-minus-one',
    name: 'Array index -1',
    language: 'C++',
    cause: 'Off-by-one',
    status: 'buried',
    severity: 'critical',
    epitaph: 'Wrote where no one should write.',
    killedBy: 'Jashanpreet',
    hoursToKill: 22,
    bornAt: '2026-01-19',
    fixMergedAt: '2026-01-27',
    buriedAt: '2026-02-05',
  },
  {
    key: 'null-profile',
    name: 'Null user on the profile page',
    language: 'Java',
    cause: 'Null reference',
    status: 'buried',
    severity: 'medium',
    epitaph: 'Nobody was home. It crashed anyway.',
    killedBy: 'Jashanpreet',
    hoursToKill: 5,
    bornAt: '2026-04-06',
    fixMergedAt: '2026-04-08',
    buriedAt: '2026-04-20',
  },

  // A zombie chain three lives long, each life starting on a daylight-saving switch.
  {
    key: 'tz-scheduler',
    name: 'Timezone bug in scheduler',
    language: 'Python',
    cause: 'Timezone',
    status: 'buried',
    severity: 'medium',
    epitaph: 'Died at 00:00 UTC. Still alive in IST.',
    killedBy: 'Jashanpreet',
    hoursToKill: 16,
    bornAt: '2025-03-30',
    fixMergedAt: '2025-04-09',
    buriedAt: '2025-04-18',
  },
  {
    key: 'tz-scheduler-z1',
    name: 'Timezone bug in scheduler (Zombie #1)',
    risesFrom: 'tz-scheduler',
    language: 'Python',
    cause: 'Timezone',
    status: 'buried',
    severity: 'critical',
    epitaph: 'Came back after daylight saving. Buried again.',
    killedBy: 'Jashanpreet',
    hoursToKill: 20,
    bornAt: '2025-10-26',
    fixMergedAt: '2025-11-05',
    buriedAt: '2025-11-14',
  },
  {
    key: 'tz-scheduler-z2',
    name: 'Timezone bug in scheduler (Zombie #2)',
    risesFrom: 'tz-scheduler-z1',
    language: 'Python',
    cause: 'Timezone',
    status: 'zombie',
    severity: 'critical',
    epitaph: 'Every time zone. Every time.',
    bornAt: '2026-03-29',
  },

  // Still walking.
  {
    key: 'stale-cache-z1',
    name: 'Stale cache after deploy (Zombie #1)',
    risesFrom: 'stale-cache',
    language: 'TypeScript',
    cause: 'Cache',
    status: 'zombie',
    severity: 'medium',
    epitaph: 'Cleared the cache. The cache remembered.',
    bornAt: '2026-08-18',
  },
]
