import type {GraveEntry} from './types'

// Your graveyard. Each entry becomes a published bug in Sanity:
//
//   npx sanity exec scripts/import-graves.ts --with-user-token -- --dry-run   check first
//   npx sanity exec scripts/import-graves.ts --with-user-token                import
//
// Re-running updates the same bugs in place. Every field is explained in ./types.ts.

export const graves: GraveEntry[] = [
  {
    key: 'loop-skipped-last',
    name: 'Loop that skipped the last item',
    language: 'Python',
    cause: 'Off-by-one',
    status: 'buried',
    component: 'reports',
    symptoms: 'The last row of every exported report was missing: the loop stopped one item early.',
    fixSummary: 'Looped over the whole list instead of stopping at length minus one.',
    severity: 'low',
    epitaph: 'Almost made it to the end. Almost.',
    killedBy: 'Jashanpreet',
    hoursToKill: 3,
    bornAt: '2024-02-12',
    fixMergedAt: '2024-02-15',
    buriedAt: '2024-02-26',
  },
  {
    key: 'undefined-not-function',
    name: 'undefined is not a function',
    language: 'JavaScript',
    cause: 'Null reference',
    status: 'buried',
    component: 'checkout',
    symptoms: 'Clicking Pay threw \'undefined is not a function\' whenever the payment script loaded late.',
    fixSummary: 'Waited for the payment script to load before calling it.',
    severity: 'medium',
    epitaph: 'It was never a function. It was never anything.',
    killedBy: 'Jashanpreet',
    hoursToKill: 2,
    bornAt: '2024-04-03',
    fixMergedAt: '2024-04-04',
    buriedAt: '2024-04-15',
  },
  {
    key: 'floating-invoice',
    name: 'The 0.1 + 0.2 invoice',
    language: 'JavaScript',
    cause: 'Floating point',
    status: 'buried',
    component: 'billing',
    symptoms: 'Invoice totals came out as 0.30000000000000004 and didn\'t match the bank\'s amounts.',
    fixSummary: 'Stored money as whole paise and only formatted it for display.',
    severity: 'critical',
    epitaph: 'Owed ₹0.30000000000000004. Paid in full.',
    killedBy: 'Jashanpreet',
    hoursToKill: 9,
    bornAt: '2024-06-17',
    fixMergedAt: '2024-06-21',
    buriedAt: '2024-07-01',
  },
  {
    key: 'div-center',
    name: 'The div that refused to center',
    language: 'CSS',
    cause: 'CSS',
    status: 'buried',
    component: 'layout',
    symptoms: 'The login card sat a few pixels left of centre on every screen size.',
    fixSummary: 'Replaced the margin hacks with a flexbox wrapper.',
    severity: 'low',
    epitaph: 'Stood slightly to the left of everything, forever.',
    killedBy: 'Jashanpreet',
    hoursToKill: 6,
    bornAt: '2024-08-05',
    fixMergedAt: '2024-08-09',
    buriedAt: '2024-08-19',
  },
  {
    key: 'my-machine',
    name: "Works only on Jashan's laptop",
    language: 'Python',
    cause: 'Works on my machine',
    status: 'buried',
    component: 'config',
    symptoms: 'The app ran on one laptop but crashed in CI with a missing environment variable.',
    fixSummary: 'Checked every required setting at startup and documented it in .env.example.',
    severity: 'medium',
    epitaph: 'It worked on my machine. Now it rests there.',
    killedBy: 'Jashanpreet',
    hoursToKill: 14,
    bornAt: '2024-09-23',
    fixMergedAt: '2024-10-01',
    buriedAt: '2024-10-10',
  },
  {
    key: 'dst-cron',
    name: 'Cron job that ran twice at DST',
    language: 'Java',
    cause: 'Timezone',
    status: 'buried',
    component: 'scheduler',
    symptoms: 'When the clocks fell back an hour, the nightly job ran twice at 01:30 and every customer got two invoices.',
    fixSummary: 'Scheduled the job in UTC and made it safe to run twice.',
    severity: 'critical',
    epitaph: 'Died twice in one night. Twice as dead.',
    killedBy: 'Jashanpreet',
    hoursToKill: 11,
    bornAt: '2024-10-27', // the night European clocks fell back an hour
    fixMergedAt: '2024-11-04',
    buriedAt: '2024-11-13',
  },
  {
    key: 'stale-cache',
    name: 'Stale cache after deploy',
    language: 'TypeScript',
    cause: 'Cache',
    status: 'buried',
    component: 'deploy',
    symptoms: 'After every deploy, pages kept showing yesterday\'s prices until the CDN cache expired.',
    fixSummary: 'Purged the CDN on deploy and versioned the asset URLs.',
    severity: 'medium',
    epitaph: 'Showed you yesterday, every day.',
    killedBy: 'Jashanpreet',
    hoursToKill: 7,
    bornAt: '2025-01-14',
    fixMergedAt: '2025-01-17',
    buriedAt: '2025-01-28',
  },
  {
    key: 'npm-install',
    name: 'npm install broke the build',
    language: 'JavaScript',
    cause: 'Dependency hell',
    status: 'buried',
    component: 'build',
    symptoms: 'A fresh npm install pulled a new version of a dependency of a dependency, and the build failed.',
    fixSummary: 'Committed the lockfile and pinned the dependency.',
    severity: 'critical',
    epitaph: 'Killed by a package it never imported.',
    killedBy: 'Jashanpreet',
    hoursToKill: 4,
    bornAt: '2025-03-10',
    fixMergedAt: '2025-03-11',
    buriedAt: '2025-03-20',
  },
  {
    key: 'race-counter',
    name: 'Two threads, one counter',
    language: 'Java',
    cause: 'Race condition',
    status: 'buried',
    component: 'analytics',
    symptoms: 'Under load, page-view counts came out lower than the real traffic.',
    fixSummary: 'Used an atomic increment instead of read, add, write.',
    severity: 'critical',
    epitaph: 'Both threads won. The counter lost.',
    killedBy: 'Jashanpreet',
    hoursToKill: 38,
    bornAt: '2025-04-22',
    fixMergedAt: '2025-05-09',
    buriedAt: '2025-05-19',
  },
  {
    key: 'while-true',
    name: 'while (true) with no break',
    language: 'C++',
    cause: 'Infinite loop',
    status: 'buried',
    component: 'worker',
    symptoms: 'The background worker pinned one CPU core at 100% and never finished its batch.',
    fixSummary: 'Added the missing break when the queue is empty.',
    severity: 'medium',
    epitaph: 'Still running. Please do not disturb.',
    killedBy: 'Jashanpreet',
    hoursToKill: 1,
    bornAt: '2025-06-30',
    fixMergedAt: '2025-07-01',
    buriedAt: '2025-07-10',
  },
  {
    key: 'emoji-username',
    name: 'Emoji broke the username',
    language: 'Python',
    cause: 'Encoding',
    status: 'buried',
    component: 'signup',
    symptoms: 'Names with emoji or accents showed up as Ã© on profiles and in emails.',
    fixSummary: 'Decoded the signup form as UTF-8 from end to end.',
    severity: 'medium',
    epitaph: "Here lies Ã©. It was once 'é'.",
    killedBy: 'Jashanpreet',
    hoursToKill: 12,
    bornAt: '2025-08-11',
    fixMergedAt: '2025-08-19',
    buriedAt: '2025-08-28',
  },
  {
    key: 'merge-head',
    name: '<<<<<<< HEAD in production',
    language: 'TypeScript',
    cause: 'Merge conflict',
    status: 'buried',
    component: 'deploy',
    symptoms: 'The homepage shipped with \'<<<<<<< HEAD\' and both versions of the header.',
    fixSummary: 'Resolved the conflict and added a CI check for conflict markers.',
    severity: 'critical',
    epitaph: 'Both versions were right. Neither survived.',
    killedBy: 'Jashanpreet',
    hoursToKill: 1,
    bornAt: '2025-11-03',
    fixMergedAt: '2025-11-04',
    buriedAt: '2025-11-12',
  },
  {
    key: 'index-minus-one',
    name: 'Array index -1',
    language: 'C++',
    cause: 'Off-by-one',
    status: 'buried',
    component: 'parser',
    symptoms: 'The parser read index -1 on empty input and overwrote the memory next to the buffer.',
    fixSummary: 'Checked for empty input before reading the last element.',
    severity: 'critical',
    epitaph: 'Wrote where no one should write.',
    killedBy: 'Jashanpreet',
    hoursToKill: 22,
    bornAt: '2026-01-19',
    fixMergedAt: '2026-01-27',
    buriedAt: '2026-02-05',
  },
  {
    key: 'null-profile',
    name: 'Null user on the profile page',
    language: 'Java',
    cause: 'Null reference',
    status: 'buried',
    component: 'profile',
    symptoms: 'Opening a deleted user\'s profile page crashed with a NullPointerException.',
    fixSummary: 'Returned a 404 when the user no longer exists.',
    severity: 'medium',
    epitaph: 'Nobody was home. It crashed anyway.',
    killedBy: 'Jashanpreet',
    hoursToKill: 5,
    bornAt: '2026-04-06',
    fixMergedAt: '2026-04-08',
    buriedAt: '2026-04-20',
  },

  // A zombie chain three lives long, each life starting on a daylight-saving switch.
  {
    key: 'tz-scheduler',
    name: 'Timezone bug in scheduler',
    language: 'Python',
    cause: 'Timezone',
    status: 'buried',
    component: 'scheduler',
    symptoms: 'Reminders fired an hour early after the clocks went forward, because times were saved without a timezone.',
    fixSummary: 'Saved reminder times in UTC along with the user\'s timezone.',
    severity: 'medium',
    epitaph: 'Died at 00:00 UTC. Still alive in IST.',
    killedBy: 'Jashanpreet',
    hoursToKill: 16,
    bornAt: '2025-03-30',
    fixMergedAt: '2025-04-09',
    buriedAt: '2025-04-18',
  },
  {
    key: 'tz-scheduler-z1',
    name: 'Timezone bug in scheduler (Zombie #1)',
    risesFrom: 'tz-scheduler',
    language: 'Python',
    cause: 'Timezone',
    status: 'buried',
    component: 'scheduler',
    symptoms: 'After the October clock change, reminders fired an hour late for everyone in Europe.',
    fixSummary: 'Recalculated the next run with the user\'s timezone rules after every clock change.',
    severity: 'critical',
    epitaph: 'Came back after daylight saving. Buried again.',
    killedBy: 'Jashanpreet',
    hoursToKill: 20,
    bornAt: '2025-10-26',
    fixMergedAt: '2025-11-05',
    buriedAt: '2025-11-14',
  },
  {
    key: 'tz-scheduler-z2',
    name: 'Timezone bug in scheduler (Zombie #2)',
    risesFrom: 'tz-scheduler-z1',
    language: 'Python',
    cause: 'Timezone',
    status: 'zombie',
    component: 'scheduler',
    symptoms: 'Since the March clock change, some reminders fire twice and some not at all.',
    severity: 'critical',
    epitaph: 'Every time zone. Every time.',
    bornAt: '2026-03-29',
  },

  // Still walking.
  {
    key: 'stale-cache-z1',
    name: 'Stale cache after deploy (Zombie #1)',
    risesFrom: 'stale-cache',
    language: 'TypeScript',
    cause: 'Cache',
    status: 'zombie',
    component: 'deploy',
    symptoms: 'Weeks after the fix, the pricing page shows yesterday\'s prices again after deploys.',
    severity: 'medium',
    epitaph: 'Cleared the cache. The cache remembered.',
    bornAt: '2026-08-18',
  },
]
