/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type LanguageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "language";
};

export type CauseOfDeathReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "causeOfDeath";
};

export type BugReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "bug";
};

export type Bug = {
  _id: string;
  _type: "bug";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  language?: LanguageReference;
  severity?: "low" | "medium" | "critical";
  component?: string;
  symptoms?: string;
  bornAt?: string;
  status: "suspected-dead" | "fix-merged" | "buried" | "zombie";
  causeOfDeath?: CauseOfDeathReference;
  killedBy?: string;
  hoursToKill?: number;
  fixSummary?: string;
  fixUrl?: string;
  fixMergedAt?: string;
  buriedAt?: string;
  epitaph?: string;
  previousLife?: BugReference;
  timesResurrected?: number;
  coronerStatus?: "awaiting approval" | "accepted";
  coronerEpitaph?: string;
  coronerCause?: CauseOfDeathReference;
  matchStatus?: "candidate" | "none" | "confirmed" | "dismissed";
  resurrectionCandidate?: BugReference;
  matchScore?: number;
  matchSignals?: Array<{
    signal?: string;
    label?: string;
    matched?: boolean;
    detail?: string;
    points?: number;
    _type: "matchSignal";
    _key: string;
  }>;
  matchReason?: string;
  publicReport?: {
    status?: "pending" | "approved";
    whatHappened?: string;
    submittedAt?: string;
  };
};

export type CauseOfDeath = {
  _id: string;
  _type: "causeOfDeath";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
};

export type Language = {
  _id: string;
  _type: "language";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  color?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LanguageReference
  | CauseOfDeathReference
  | BugReference
  | Bug
  | CauseOfDeath
  | Language
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: GRAVEYARD_QUERY
// Query: *[_type == "bug" && !(defined(publicReport) && publicReport.status == "pending")    && (!defined($language) || language->name == $language)    && (!defined($cause) || causeOfDeath->title == $cause)  ] | order(coalesce(buriedAt, fixMergedAt, bornAt) desc, name asc) {    _id,    name,    "slug": slug.current,    status,    epitaph,    bornAt,    fixMergedAt,    buriedAt,    language->{name, color},    causeOfDeath->{title},    "previousLife": previousLife->{name},    "disturbed": count(*[_type == "bug" && previousLife._ref == ^._id]) > 0,    "haunted": count(*[_type == "bug" && matchStatus == "candidate" && resurrectionCandidate._ref == ^._id]) > 0  }
export type GRAVEYARD_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
  epitaph: string | null;
  bornAt: string | null;
  fixMergedAt: string | null;
  buriedAt: string | null;
  language: {
    name: string;
    color: string | null;
  } | null;
  causeOfDeath: {
    title: string;
  } | null;
  previousLife: {
    name: string;
  } | null;
  disturbed: boolean;
  haunted: boolean;
}>;

// Source: sanity/lib/queries.ts
// Variable: GRAVE_QUERY
// Query: *[_type == "bug" && slug.current == $slug && !(defined(publicReport) && publicReport.status == "pending")][0] {    _id,    name,    "slug": slug.current,    status,    severity,    epitaph,    killedBy,    hoursToKill,    bornAt,    fixMergedAt,    buriedAt,    timesResurrected,    component,    symptoms,    fixSummary,    fixUrl,    language->{name, color},    causeOfDeath->{title, description},    "haunting": *[_type == "bug" && matchStatus == "candidate" && resurrectionCandidate._ref == ^._id]      | order(_createdAt desc)[0]{name, matchScore, "reportedAt": coalesce(publicReport.submittedAt, _createdAt)},    "previousLife": previousLife->{      name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,      "previousLife": previousLife->{        name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,        "previousLife": previousLife->{          name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,          "hasOlderLives": defined(previousLife)        }      }    },    "risen": *[_type == "bug" && previousLife._ref == ^._id] | order(bornAt asc) {      name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,      "disturbed": count(*[_type == "bug" && previousLife._ref == ^._id]) > 0    }  }
export type GRAVE_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
  severity: "critical" | "low" | "medium" | null;
  epitaph: string | null;
  killedBy: string | null;
  hoursToKill: number | null;
  bornAt: string | null;
  fixMergedAt: string | null;
  buriedAt: string | null;
  timesResurrected: number | null;
  component: string | null;
  symptoms: string | null;
  fixSummary: string | null;
  fixUrl: string | null;
  language: {
    name: string;
    color: string | null;
  } | null;
  causeOfDeath: {
    title: string;
    description: string | null;
  } | null;
  haunting: {
    name: string;
    matchScore: number | null;
    reportedAt: string;
  } | null;
  previousLife: {
    name: string;
    slug: string;
    epitaph: string | null;
    status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
    bornAt: string | null;
    fixMergedAt: string | null;
    buriedAt: string | null;
    previousLife: {
      name: string;
      slug: string;
      epitaph: string | null;
      status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
      bornAt: string | null;
      fixMergedAt: string | null;
      buriedAt: string | null;
      previousLife: {
        name: string;
        slug: string;
        epitaph: string | null;
        status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
        bornAt: string | null;
        fixMergedAt: string | null;
        buriedAt: string | null;
        hasOlderLives: false | true;
      } | null;
    } | null;
  } | null;
  risen: Array<{
    name: string;
    slug: string;
    epitaph: string | null;
    status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
    bornAt: string | null;
    fixMergedAt: string | null;
    buriedAt: string | null;
    disturbed: boolean;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: LEADERBOARD_QUERY
// Query: {  "deadliest": *[_type == "bug" && defined(hoursToKill) && !(defined(publicReport) && publicReport.status == "pending")] | order(hoursToKill desc, name asc) [0...5] {    name,    "slug": slug.current,    hoursToKill,    language->{name, color}  },  "hauntedLanguages": *[_type == "language"] {    name,    color,    "zombies": count(*[_type == "bug" && defined(previousLife) && language._ref == ^._id && !(defined(publicReport) && publicReport.status == "pending")])  } [zombies > 0] | order(zombies desc, name asc),  "causes": *[_type == "causeOfDeath"] {    title,    "bugs": count(*[_type == "bug" && causeOfDeath._ref == ^._id && !(defined(publicReport) && publicReport.status == "pending")])  } [bugs > 0] | order(bugs desc, title asc),  "mostResurrected": *[_type == "bug" && timesResurrected > 0 && !(defined(publicReport) && publicReport.status == "pending")] | order(timesResurrected desc, bornAt desc) [0] {    name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,    timesResurrected,    "previousLife": previousLife->{      name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,      "previousLife": previousLife->{        name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,        "previousLife": previousLife->{          name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,          "hasOlderLives": defined(previousLife)        }      }    }  }}
export type LEADERBOARD_QUERY_RESULT = {
  deadliest: Array<{
    name: string;
    slug: string;
    hoursToKill: number | null;
    language: {
      name: string;
      color: string | null;
    } | null;
  }>;
  hauntedLanguages: Array<{
    name: string;
    color: string | null;
    zombies: number;
  }>;
  causes: Array<{
    title: string;
    bugs: number;
  }>;
  mostResurrected: {
    name: string;
    slug: string;
    epitaph: string | null;
    status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
    bornAt: string | null;
    fixMergedAt: string | null;
    buriedAt: string | null;
    timesResurrected: number | null;
    previousLife: {
      name: string;
      slug: string;
      epitaph: string | null;
      status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
      bornAt: string | null;
      fixMergedAt: string | null;
      buriedAt: string | null;
      previousLife: {
        name: string;
        slug: string;
        epitaph: string | null;
        status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
        bornAt: string | null;
        fixMergedAt: string | null;
        buriedAt: string | null;
        previousLife: {
          name: string;
          slug: string;
          epitaph: string | null;
          status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
          bornAt: string | null;
          fixMergedAt: string | null;
          buriedAt: string | null;
          hasOlderLives: false | true;
        } | null;
      } | null;
    } | null;
  } | null;
};

// Source: sanity/lib/queries.ts
// Variable: GRAVE_OG_QUERY
// Query: *[_type == "bug" && slug.current == $slug && !(defined(publicReport) && publicReport.status == "pending")][0] {    name,    epitaph,    status,    bornAt,    fixMergedAt,    buriedAt,    "language": language->name,    "causeOfDeath": causeOfDeath->title,    "risenFrom": previousLife->name,    "disturbed": count(*[_type == "bug" && previousLife._ref == ^._id]) > 0  }
export type GRAVE_OG_QUERY_RESULT = {
  name: string;
  epitaph: string | null;
  status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
  bornAt: string | null;
  fixMergedAt: string | null;
  buriedAt: string | null;
  language: string | null;
  causeOfDeath: string | null;
  risenFrom: string | null;
  disturbed: boolean;
} | null;

// Source: sanity/lib/queries.ts
// Variable: GRAVE_SLUGS_QUERY
// Query: *[_type == "bug" && defined(slug.current) && !(defined(publicReport) && publicReport.status == "pending")] {"slug": slug.current}
export type GRAVE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: GRAVEYARD_FILTERS_QUERY
// Query: {  "languages": *[_type == "language"] | order(name asc) {    name,    color,    "count": count(*[_type == "bug" && language._ref == ^._id && !(defined(publicReport) && publicReport.status == "pending")])  },  "causes": *[_type == "causeOfDeath"] | order(title asc) {    title,    "count": count(*[_type == "bug" && causeOfDeath._ref == ^._id && !(defined(publicReport) && publicReport.status == "pending")])  }}
export type GRAVEYARD_FILTERS_QUERY_RESULT = {
  languages: Array<{
    name: string;
    color: string | null;
    count: number;
  }>;
  causes: Array<{
    title: string;
    count: number;
  }>;
};

// Source: sanity/lib/queries.ts
// Variable: REPORT_PAGE_QUERY
// Query: {  "languages": *[_type == "language"] | order(name asc) {_id, name},  "pending": *[_type == "bug" && publicReport.status == "pending"] | order(publicReport.submittedAt desc) [0...20] {    _id,    name,    "language": language->name,    "whatHappened": publicReport.whatHappened,    "submittedAt": publicReport.submittedAt,    coronerStatus,    coronerEpitaph,    "coronerCause": coronerCause->title,    matchStatus,    matchScore,    matchReason,    matchSignals[]{_key, label, matched, detail, points},    "candidate": resurrectionCandidate->{name, "slug": slug.current, fixSummary, fixUrl}  },  "components": array::unique(*[_type == "bug" && defined(component) && !(defined(publicReport) && publicReport.status == "pending")].component)}
export type REPORT_PAGE_QUERY_RESULT = {
  languages: Array<{
    _id: string;
    name: string;
  }>;
  pending: Array<{
    _id: string;
    name: string;
    language: string | null;
    whatHappened: string | null;
    submittedAt: string | null;
    coronerStatus: "accepted" | "awaiting approval" | null;
    coronerEpitaph: string | null;
    coronerCause: string | null;
    matchStatus: "candidate" | "confirmed" | "dismissed" | "none" | null;
    matchScore: number | null;
    matchReason: string | null;
    matchSignals: Array<{
      _key: string;
      label: string | null;
      matched: boolean | null;
      detail: string | null;
      points: number | null;
    }> | null;
    candidate: {
      name: string;
      slug: string;
      fixSummary: string | null;
      fixUrl: string | null;
    } | null;
  }>;
  components: Array<string | null>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "bug" && !(defined(publicReport) && publicReport.status == "pending")\n    && (!defined($language) || language->name == $language)\n    && (!defined($cause) || causeOfDeath->title == $cause)\n  ] | order(coalesce(buriedAt, fixMergedAt, bornAt) desc, name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    status,\n    epitaph,\n    bornAt,\n    fixMergedAt,\n    buriedAt,\n    language->{name, color},\n    causeOfDeath->{title},\n    "previousLife": previousLife->{name},\n    "disturbed": count(*[_type == "bug" && previousLife._ref == ^._id]) > 0,\n    "haunted": count(*[_type == "bug" && matchStatus == "candidate" && resurrectionCandidate._ref == ^._id]) > 0\n  }\n': GRAVEYARD_QUERY_RESULT;
    '\n  *[_type == "bug" && slug.current == $slug && !(defined(publicReport) && publicReport.status == "pending")][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    status,\n    severity,\n    epitaph,\n    killedBy,\n    hoursToKill,\n    bornAt,\n    fixMergedAt,\n    buriedAt,\n    timesResurrected,\n    component,\n    symptoms,\n    fixSummary,\n    fixUrl,\n    language->{name, color},\n    causeOfDeath->{title, description},\n    "haunting": *[_type == "bug" && matchStatus == "candidate" && resurrectionCandidate._ref == ^._id]\n      | order(_createdAt desc)[0]{name, matchScore, "reportedAt": coalesce(publicReport.submittedAt, _createdAt)},\n    "previousLife": previousLife->{\n      name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,\n      "previousLife": previousLife->{\n        name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,\n        "previousLife": previousLife->{\n          name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,\n          "hasOlderLives": defined(previousLife)\n        }\n      }\n    },\n    "risen": *[_type == "bug" && previousLife._ref == ^._id] | order(bornAt asc) {\n      name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,\n      "disturbed": count(*[_type == "bug" && previousLife._ref == ^._id]) > 0\n    }\n  }\n': GRAVE_QUERY_RESULT;
    '{\n  "deadliest": *[_type == "bug" && defined(hoursToKill) && !(defined(publicReport) && publicReport.status == "pending")] | order(hoursToKill desc, name asc) [0...5] {\n    name,\n    "slug": slug.current,\n    hoursToKill,\n    language->{name, color}\n  },\n  "hauntedLanguages": *[_type == "language"] {\n    name,\n    color,\n    "zombies": count(*[_type == "bug" && defined(previousLife) && language._ref == ^._id && !(defined(publicReport) && publicReport.status == "pending")])\n  } [zombies > 0] | order(zombies desc, name asc),\n  "causes": *[_type == "causeOfDeath"] {\n    title,\n    "bugs": count(*[_type == "bug" && causeOfDeath._ref == ^._id && !(defined(publicReport) && publicReport.status == "pending")])\n  } [bugs > 0] | order(bugs desc, title asc),\n  "mostResurrected": *[_type == "bug" && timesResurrected > 0 && !(defined(publicReport) && publicReport.status == "pending")] | order(timesResurrected desc, bornAt desc) [0] {\n    name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,\n    timesResurrected,\n    "previousLife": previousLife->{\n      name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,\n      "previousLife": previousLife->{\n        name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,\n        "previousLife": previousLife->{\n          name, "slug": slug.current, epitaph, status, bornAt, fixMergedAt, buriedAt,\n          "hasOlderLives": defined(previousLife)\n        }\n      }\n    }\n  }\n}': LEADERBOARD_QUERY_RESULT;
    '\n  *[_type == "bug" && slug.current == $slug && !(defined(publicReport) && publicReport.status == "pending")][0] {\n    name,\n    epitaph,\n    status,\n    bornAt,\n    fixMergedAt,\n    buriedAt,\n    "language": language->name,\n    "causeOfDeath": causeOfDeath->title,\n    "risenFrom": previousLife->name,\n    "disturbed": count(*[_type == "bug" && previousLife._ref == ^._id]) > 0\n  }\n': GRAVE_OG_QUERY_RESULT;
    '\n  *[_type == "bug" && defined(slug.current) && !(defined(publicReport) && publicReport.status == "pending")] {"slug": slug.current}\n': GRAVE_SLUGS_QUERY_RESULT;
    '{\n  "languages": *[_type == "language"] | order(name asc) {\n    name,\n    color,\n    "count": count(*[_type == "bug" && language._ref == ^._id && !(defined(publicReport) && publicReport.status == "pending")])\n  },\n  "causes": *[_type == "causeOfDeath"] | order(title asc) {\n    title,\n    "count": count(*[_type == "bug" && causeOfDeath._ref == ^._id && !(defined(publicReport) && publicReport.status == "pending")])\n  }\n}': GRAVEYARD_FILTERS_QUERY_RESULT;
    '{\n  "languages": *[_type == "language"] | order(name asc) {_id, name},\n  "pending": *[_type == "bug" && publicReport.status == "pending"] | order(publicReport.submittedAt desc) [0...20] {\n    _id,\n    name,\n    "language": language->name,\n    "whatHappened": publicReport.whatHappened,\n    "submittedAt": publicReport.submittedAt,\n    coronerStatus,\n    coronerEpitaph,\n    "coronerCause": coronerCause->title,\n    matchStatus,\n    matchScore,\n    matchReason,\n    matchSignals[]{_key, label, matched, detail, points},\n    "candidate": resurrectionCandidate->{name, "slug": slug.current, fixSummary, fixUrl}\n  },\n  "components": array::unique(*[_type == "bug" && defined(component) && !(defined(publicReport) && publicReport.status == "pending")].component)\n}': REPORT_PAGE_QUERY_RESULT;
  }
}
