/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type LanguageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "language";
};

export type CauseOfDeathReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "causeOfDeath";
};

export type BugReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "bug";
};

export type Bug = {
  _id: string;
  _type: "bug";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  language?: LanguageReference;
  severity?: "low" | "medium" | "critical";
  bornAt?: string;
  status: "suspected-dead" | "fix-merged" | "buried" | "zombie";
  causeOfDeath?: CauseOfDeathReference;
  killedBy?: string;
  hoursToKill?: number;
  fixMergedAt?: string;
  buriedAt?: string;
  epitaph?: string;
  previousLife?: BugReference;
  timesResurrected?: number;
};

export type CauseOfDeath = {
  _id: string;
  _type: "causeOfDeath";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
};

export type Language = {
  _id: string;
  _type: "language";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  color?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LanguageReference
  | CauseOfDeathReference
  | BugReference
  | Bug
  | CauseOfDeath
  | Language
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: GRAVEYARD_QUERY
// Query: *[_type == "bug"    && (!defined($language) || language->name == $language)    && (!defined($cause) || causeOfDeath->title == $cause)  ] | order(coalesce(buriedAt, fixMergedAt, bornAt) desc, name asc) {    _id,    name,    "slug": slug.current,    status,    epitaph,    bornAt,    fixMergedAt,    buriedAt,    language->{name, color},    causeOfDeath->{title},    "previousLife": previousLife->{name},    "disturbed": count(*[_type == "bug" && previousLife._ref == ^._id]) > 0  }
export type GRAVEYARD_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  status: "buried" | "fix-merged" | "suspected-dead" | "zombie";
  epitaph: string | null;
  bornAt: string | null;
  fixMergedAt: string | null;
  buriedAt: string | null;
  language: {
    name: string;
    color: string | null;
  } | null;
  causeOfDeath: {
    title: string;
  } | null;
  previousLife: {
    name: string;
  } | null;
  disturbed: boolean;
}>;

// Source: sanity/lib/queries.ts
// Variable: GRAVEYARD_FILTERS_QUERY
// Query: {  "languages": *[_type == "language"] | order(name asc) {    name,    color,    "count": count(*[_type == "bug" && language._ref == ^._id])  },  "causes": *[_type == "causeOfDeath"] | order(title asc) {    title,    "count": count(*[_type == "bug" && causeOfDeath._ref == ^._id])  }}
export type GRAVEYARD_FILTERS_QUERY_RESULT = {
  languages: Array<{
    name: string;
    color: string | null;
    count: number;
  }>;
  causes: Array<{
    title: string;
    count: number;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "bug"\n    && (!defined($language) || language->name == $language)\n    && (!defined($cause) || causeOfDeath->title == $cause)\n  ] | order(coalesce(buriedAt, fixMergedAt, bornAt) desc, name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    status,\n    epitaph,\n    bornAt,\n    fixMergedAt,\n    buriedAt,\n    language->{name, color},\n    causeOfDeath->{title},\n    "previousLife": previousLife->{name},\n    "disturbed": count(*[_type == "bug" && previousLife._ref == ^._id]) > 0\n  }\n': GRAVEYARD_QUERY_RESULT;
    '{\n  "languages": *[_type == "language"] | order(name asc) {\n    name,\n    color,\n    "count": count(*[_type == "bug" && language._ref == ^._id])\n  },\n  "causes": *[_type == "causeOfDeath"] | order(title asc) {\n    title,\n    "count": count(*[_type == "bug" && causeOfDeath._ref == ^._id])\n  }\n}': GRAVEYARD_FILTERS_QUERY_RESULT;
  }
}
